renamedirs = [ "[repo]/src/nibstandard",]
editlines = [ 
[ "[repo]/Makefile", "APPNAME=\"nibstandard\"", "APPNAME=\"[newname]\"",],
[ "[repo]/pyproject.toml", "name = \"nibstandard\"", "name = \"[newname]\"",],
[ "[repo]/pyproject.toml", "packages = [{include = \"nibstandard\", from = \"src\"}]", "packages = [{include = \"[newname]\", from = \"src\"}]",],
[ "[repo]/pyproject.toml", "nibstandard = 'nibstandard.ux.cli:cli'", "[newname] = '[newname].cli:cli'",],
]
inherited = [
"LICENSE",
"MANIFEST.in",
".gitignore",
]
