renamedirs = [ "[repo]/src/warehouse",]
editlines = []
inherited = [
"LICENSE",
"MANIFEST.in",
".gitignore",
"poetry.toml",
]
semiinherited = [
"Makefile",
"pyproject.toml",
"setup.cfg",
"setup.py",
"Taskfile.yml",
]
