renamedirs = [ "[repo]/src/warehouse",]
editlines = [ 
[ "[repo]/Makefile", "APPNAME=\"warehouse\"", "APPNAME=\"[newname]\"",],
[ "[repo]/pyproject.toml", "name = \"warehouse\"", "name = \"[newname]\"",],
[ "[repo]/pyproject.toml", "packages = [{include = \"warehouse\", from = \"src\"}]", "packages = [{include = \"[newname]\", from = \"src\"}]",],
[ "[repo]/pyproject.toml", "warehouse = 'warehouse.ux.cli:cli'", "[newname] = '[newname].cli:cli'",],
]
inherited = [
"LICENSE",
"MANIFEST.in",
".gitignore",
]
